// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kubernetes-csi/csi-proxy/client/api/disk/v1alpha1/api.proto

package v1alpha1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListDiskLocationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDiskLocationsRequest) Reset()         { *m = ListDiskLocationsRequest{} }
func (m *ListDiskLocationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListDiskLocationsRequest) ProtoMessage()    {}
func (*ListDiskLocationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_028ab8065db229af, []int{0}
}

func (m *ListDiskLocationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDiskLocationsRequest.Unmarshal(m, b)
}
func (m *ListDiskLocationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDiskLocationsRequest.Marshal(b, m, deterministic)
}
func (m *ListDiskLocationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDiskLocationsRequest.Merge(m, src)
}
func (m *ListDiskLocationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListDiskLocationsRequest.Size(m)
}
func (m *ListDiskLocationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDiskLocationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDiskLocationsRequest proto.InternalMessageInfo

type DiskLocation struct {
	Adapter              string   `protobuf:"bytes,1,opt,name=Adapter,proto3" json:"Adapter,omitempty"`
	Bus                  string   `protobuf:"bytes,2,opt,name=Bus,proto3" json:"Bus,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=Target,proto3" json:"Target,omitempty"`
	LUNID                string   `protobuf:"bytes,4,opt,name=LUNID,proto3" json:"LUNID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskLocation) Reset()         { *m = DiskLocation{} }
func (m *DiskLocation) String() string { return proto.CompactTextString(m) }
func (*DiskLocation) ProtoMessage()    {}
func (*DiskLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_028ab8065db229af, []int{1}
}

func (m *DiskLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskLocation.Unmarshal(m, b)
}
func (m *DiskLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskLocation.Marshal(b, m, deterministic)
}
func (m *DiskLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskLocation.Merge(m, src)
}
func (m *DiskLocation) XXX_Size() int {
	return xxx_messageInfo_DiskLocation.Size(m)
}
func (m *DiskLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskLocation.DiscardUnknown(m)
}

var xxx_messageInfo_DiskLocation proto.InternalMessageInfo

func (m *DiskLocation) GetAdapter() string {
	if m != nil {
		return m.Adapter
	}
	return ""
}

func (m *DiskLocation) GetBus() string {
	if m != nil {
		return m.Bus
	}
	return ""
}

func (m *DiskLocation) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *DiskLocation) GetLUNID() string {
	if m != nil {
		return m.LUNID
	}
	return ""
}

type ListDiskLocationsResponse struct {
	// Map of disk device IDs and <adapter, bus, target, lun ID> associated with each disk device
	DiskLocations        map[string]*DiskLocation `protobuf:"bytes,1,rep,name=disk_locations,json=diskLocations,proto3" json:"disk_locations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListDiskLocationsResponse) Reset()         { *m = ListDiskLocationsResponse{} }
func (m *ListDiskLocationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListDiskLocationsResponse) ProtoMessage()    {}
func (*ListDiskLocationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_028ab8065db229af, []int{2}
}

func (m *ListDiskLocationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDiskLocationsResponse.Unmarshal(m, b)
}
func (m *ListDiskLocationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDiskLocationsResponse.Marshal(b, m, deterministic)
}
func (m *ListDiskLocationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDiskLocationsResponse.Merge(m, src)
}
func (m *ListDiskLocationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListDiskLocationsResponse.Size(m)
}
func (m *ListDiskLocationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDiskLocationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDiskLocationsResponse proto.InternalMessageInfo

func (m *ListDiskLocationsResponse) GetDiskLocations() map[string]*DiskLocation {
	if m != nil {
		return m.DiskLocations
	}
	return nil
}

type ListDiskIDsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDiskIDsRequest) Reset()         { *m = ListDiskIDsRequest{} }
func (m *ListDiskIDsRequest) String() string { return proto.CompactTextString(m) }
func (*ListDiskIDsRequest) ProtoMessage()    {}
func (*ListDiskIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_028ab8065db229af, []int{3}
}

func (m *ListDiskIDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDiskIDsRequest.Unmarshal(m, b)
}
func (m *ListDiskIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDiskIDsRequest.Marshal(b, m, deterministic)
}
func (m *ListDiskIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDiskIDsRequest.Merge(m, src)
}
func (m *ListDiskIDsRequest) XXX_Size() int {
	return xxx_messageInfo_ListDiskIDsRequest.Size(m)
}
func (m *ListDiskIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDiskIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDiskIDsRequest proto.InternalMessageInfo

type DiskIDList struct {
	// List of node metrics.
	IDs                  []string `protobuf:"bytes,2,rep,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskIDList) Reset()         { *m = DiskIDList{} }
func (m *DiskIDList) String() string { return proto.CompactTextString(m) }
func (*DiskIDList) ProtoMessage()    {}
func (*DiskIDList) Descriptor() ([]byte, []int) {
	return fileDescriptor_028ab8065db229af, []int{4}
}

func (m *DiskIDList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskIDList.Unmarshal(m, b)
}
func (m *DiskIDList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskIDList.Marshal(b, m, deterministic)
}
func (m *DiskIDList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskIDList.Merge(m, src)
}
func (m *DiskIDList) XXX_Size() int {
	return xxx_messageInfo_DiskIDList.Size(m)
}
func (m *DiskIDList) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskIDList.DiscardUnknown(m)
}

var xxx_messageInfo_DiskIDList proto.InternalMessageInfo

func (m *DiskIDList) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

type ListDiskIDsResponse struct {
	// Map of disk device IDs and SCSI IDs associated with each disk device
	Disk_IDs             map[string]*DiskIDList `protobuf:"bytes,1,rep,name=disk_IDs,json=diskIDs,proto3" json:"disk_IDs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListDiskIDsResponse) Reset()         { *m = ListDiskIDsResponse{} }
func (m *ListDiskIDsResponse) String() string { return proto.CompactTextString(m) }
func (*ListDiskIDsResponse) ProtoMessage()    {}
func (*ListDiskIDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_028ab8065db229af, []int{5}
}

func (m *ListDiskIDsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDiskIDsResponse.Unmarshal(m, b)
}
func (m *ListDiskIDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDiskIDsResponse.Marshal(b, m, deterministic)
}
func (m *ListDiskIDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDiskIDsResponse.Merge(m, src)
}
func (m *ListDiskIDsResponse) XXX_Size() int {
	return xxx_messageInfo_ListDiskIDsResponse.Size(m)
}
func (m *ListDiskIDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDiskIDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDiskIDsResponse proto.InternalMessageInfo

func (m *ListDiskIDsResponse) GetDisk_IDs() map[string]*DiskIDList {
	if m != nil {
		return m.Disk_IDs
	}
	return nil
}

type PartitionDiskRequest struct {
	// Disk device ID of the disk to partition
	DiskId               string   `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionDiskRequest) Reset()         { *m = PartitionDiskRequest{} }
func (m *PartitionDiskRequest) String() string { return proto.CompactTextString(m) }
func (*PartitionDiskRequest) ProtoMessage()    {}
func (*PartitionDiskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_028ab8065db229af, []int{6}
}

func (m *PartitionDiskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionDiskRequest.Unmarshal(m, b)
}
func (m *PartitionDiskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionDiskRequest.Marshal(b, m, deterministic)
}
func (m *PartitionDiskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionDiskRequest.Merge(m, src)
}
func (m *PartitionDiskRequest) XXX_Size() int {
	return xxx_messageInfo_PartitionDiskRequest.Size(m)
}
func (m *PartitionDiskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionDiskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionDiskRequest proto.InternalMessageInfo

func (m *PartitionDiskRequest) GetDiskId() string {
	if m != nil {
		return m.DiskId
	}
	return ""
}

type PartitionDiskResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionDiskResponse) Reset()         { *m = PartitionDiskResponse{} }
func (m *PartitionDiskResponse) String() string { return proto.CompactTextString(m) }
func (*PartitionDiskResponse) ProtoMessage()    {}
func (*PartitionDiskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_028ab8065db229af, []int{7}
}

func (m *PartitionDiskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionDiskResponse.Unmarshal(m, b)
}
func (m *PartitionDiskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionDiskResponse.Marshal(b, m, deterministic)
}
func (m *PartitionDiskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionDiskResponse.Merge(m, src)
}
func (m *PartitionDiskResponse) XXX_Size() int {
	return xxx_messageInfo_PartitionDiskResponse.Size(m)
}
func (m *PartitionDiskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionDiskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionDiskResponse proto.InternalMessageInfo

type RescanRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RescanRequest) Reset()         { *m = RescanRequest{} }
func (m *RescanRequest) String() string { return proto.CompactTextString(m) }
func (*RescanRequest) ProtoMessage()    {}
func (*RescanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_028ab8065db229af, []int{8}
}

func (m *RescanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RescanRequest.Unmarshal(m, b)
}
func (m *RescanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RescanRequest.Marshal(b, m, deterministic)
}
func (m *RescanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RescanRequest.Merge(m, src)
}
func (m *RescanRequest) XXX_Size() int {
	return xxx_messageInfo_RescanRequest.Size(m)
}
func (m *RescanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RescanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RescanRequest proto.InternalMessageInfo

type RescanResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RescanResponse) Reset()         { *m = RescanResponse{} }
func (m *RescanResponse) String() string { return proto.CompactTextString(m) }
func (*RescanResponse) ProtoMessage()    {}
func (*RescanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_028ab8065db229af, []int{9}
}

func (m *RescanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RescanResponse.Unmarshal(m, b)
}
func (m *RescanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RescanResponse.Marshal(b, m, deterministic)
}
func (m *RescanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RescanResponse.Merge(m, src)
}
func (m *RescanResponse) XXX_Size() int {
	return xxx_messageInfo_RescanResponse.Size(m)
}
func (m *RescanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RescanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RescanResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListDiskLocationsRequest)(nil), "v1alpha1.ListDiskLocationsRequest")
	proto.RegisterType((*DiskLocation)(nil), "v1alpha1.DiskLocation")
	proto.RegisterType((*ListDiskLocationsResponse)(nil), "v1alpha1.ListDiskLocationsResponse")
	proto.RegisterMapType((map[string]*DiskLocation)(nil), "v1alpha1.ListDiskLocationsResponse.DiskLocationsEntry")
	proto.RegisterType((*ListDiskIDsRequest)(nil), "v1alpha1.ListDiskIDsRequest")
	proto.RegisterType((*DiskIDList)(nil), "v1alpha1.DiskIDList")
	proto.RegisterType((*ListDiskIDsResponse)(nil), "v1alpha1.ListDiskIDsResponse")
	proto.RegisterMapType((map[string]*DiskIDList)(nil), "v1alpha1.ListDiskIDsResponse.DiskIDsEntry")
	proto.RegisterType((*PartitionDiskRequest)(nil), "v1alpha1.PartitionDiskRequest")
	proto.RegisterType((*PartitionDiskResponse)(nil), "v1alpha1.PartitionDiskResponse")
	proto.RegisterType((*RescanRequest)(nil), "v1alpha1.RescanRequest")
	proto.RegisterType((*RescanResponse)(nil), "v1alpha1.RescanResponse")
}

func init() {
	proto.RegisterFile("github.com/kubernetes-csi/csi-proxy/client/api/disk/v1alpha1/api.proto", fileDescriptor_028ab8065db229af)
}

var fileDescriptor_028ab8065db229af = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xd1, 0x6e, 0xd3, 0x4a,
	0x10, 0xad, 0x93, 0x36, 0xed, 0x9d, 0xdc, 0x94, 0x32, 0x84, 0xc6, 0x58, 0x50, 0xaa, 0xe5, 0xa5,
	0xaa, 0xa8, 0xad, 0x06, 0x09, 0x21, 0x24, 0x1e, 0x40, 0x2e, 0x52, 0xa4, 0x08, 0x55, 0x16, 0x48,
	0xbc, 0x40, 0xb5, 0xb1, 0x57, 0xcd, 0x2a, 0xc1, 0x36, 0xde, 0x75, 0x45, 0x7e, 0x8a, 0xdf, 0xe0,
	0x07, 0xf8, 0x20, 0xb4, 0xbb, 0xde, 0xc6, 0x26, 0x49, 0xc5, 0x9b, 0xe7, 0xcc, 0x9c, 0x99, 0x39,
	0x67, 0x56, 0x86, 0xf7, 0xd7, 0x5c, 0x4e, 0xcb, 0x89, 0x1f, 0x67, 0xdf, 0x82, 0x59, 0x39, 0x61,
	0x45, 0xca, 0x24, 0x13, 0x67, 0xb1, 0xe0, 0x41, 0x2c, 0xf8, 0x59, 0x5e, 0x64, 0x3f, 0x16, 0x41,
	0x3c, 0xe7, 0x2c, 0x95, 0x01, 0xcd, 0x79, 0x90, 0x70, 0x31, 0x0b, 0x6e, 0xce, 0xe9, 0x3c, 0x9f,
	0xd2, 0x73, 0x85, 0xf8, 0x79, 0x91, 0xc9, 0x0c, 0xf7, 0x2c, 0x46, 0x3c, 0x70, 0xc7, 0x5c, 0xc8,
	0x90, 0x8b, 0xd9, 0x38, 0x8b, 0xa9, 0xe4, 0x59, 0x2a, 0x22, 0xf6, 0xbd, 0x64, 0x42, 0x92, 0x29,
	0xfc, 0x5f, 0xc7, 0xd1, 0x85, 0xdd, 0xb7, 0x09, 0xcd, 0x25, 0x2b, 0x5c, 0xe7, 0xd8, 0x39, 0xf9,
	0x2f, 0xb2, 0x21, 0x1e, 0x40, 0xfb, 0x5d, 0x29, 0xdc, 0x96, 0x46, 0xd5, 0x27, 0x1e, 0x42, 0xe7,
	0x23, 0x2d, 0xae, 0x99, 0x74, 0xdb, 0x1a, 0xac, 0x22, 0xec, 0xc3, 0xce, 0xf8, 0xd3, 0x87, 0x51,
	0xe8, 0x6e, 0x6b, 0xd8, 0x04, 0xe4, 0xb7, 0x03, 0x8f, 0xd6, 0xac, 0x21, 0xf2, 0x2c, 0x15, 0x0c,
	0xbf, 0xc0, 0xbe, 0x12, 0x72, 0x35, 0xb7, 0x19, 0xd7, 0x39, 0x6e, 0x9f, 0x74, 0x87, 0x2f, 0x7d,
	0x2b, 0xc3, 0xdf, 0x48, 0xf6, 0x1b, 0xe8, 0x45, 0x2a, 0x8b, 0x45, 0xd4, 0x4b, 0xea, 0x98, 0xf7,
	0x19, 0x70, 0xb5, 0x48, 0x49, 0x9a, 0xb1, 0x45, 0x25, 0x54, 0x7d, 0xe2, 0x73, 0xd8, 0xb9, 0xa1,
	0xf3, 0x92, 0x69, 0x99, 0xdd, 0xe1, 0xe1, 0x72, 0x7a, 0x9d, 0x1e, 0x99, 0xa2, 0xd7, 0xad, 0x57,
	0x0e, 0xe9, 0x03, 0xda, 0xc5, 0x46, 0xe1, 0xad, 0xad, 0x47, 0x00, 0x06, 0x51, 0x39, 0x35, 0x67,
	0x14, 0x2a, 0xeb, 0xda, 0x6a, 0xce, 0x28, 0x14, 0xe4, 0xa7, 0x03, 0x0f, 0x1a, 0xb4, 0xca, 0x86,
	0x0b, 0xd8, 0xd3, 0x36, 0xa8, 0x72, 0x63, 0xc0, 0xe9, 0xaa, 0x01, 0x35, 0x82, 0x5f, 0xc5, 0x46,
	0xf4, 0x6e, 0x62, 0x22, 0xef, 0xd2, 0x5c, 0xd5, 0x26, 0xd6, 0x08, 0x3d, 0x6d, 0x0a, 0xed, 0x37,
	0x85, 0x9a, 0xbd, 0xeb, 0x32, 0x03, 0xe8, 0x5f, 0xd2, 0x42, 0x72, 0x25, 0x5f, 0x55, 0x54, 0x42,
	0x71, 0x00, 0x7a, 0xe8, 0x15, 0x4f, 0xaa, 0xee, 0x1d, 0xbd, 0x43, 0x42, 0x06, 0xf0, 0xf0, 0x2f,
	0x82, 0xd9, 0x98, 0xdc, 0x83, 0x5e, 0xc4, 0x44, 0x4c, 0x53, 0xeb, 0xd5, 0x01, 0xec, 0x5b, 0xc0,
	0x94, 0x0c, 0x7f, 0xb5, 0x60, 0x5b, 0x71, 0xf0, 0x2b, 0xdc, 0x5f, 0xb9, 0x3a, 0x92, 0x3b, 0x9f,
	0x84, 0xee, 0xe9, 0x3d, 0xfb, 0x87, 0x67, 0x43, 0xb6, 0x70, 0x0c, 0xdd, 0x9a, 0xa9, 0xf8, 0x78,
	0x83, 0xd7, 0xa6, 0xe7, 0x93, 0x3b, 0x2f, 0x41, 0xb6, 0x30, 0x82, 0x5e, 0x43, 0x32, 0x1e, 0x2d,
	0x19, 0xeb, 0xcc, 0xf3, 0x9e, 0x6e, 0xcc, 0xdf, 0xf6, 0x7c, 0x03, 0x1d, 0x63, 0x0e, 0x0e, 0x96,
	0xc5, 0x0d, 0xff, 0x3c, 0x77, 0x35, 0x61, 0xe9, 0x93, 0x8e, 0xfe, 0x17, 0xbc, 0xf8, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xfb, 0xe0, 0xac, 0x7f, 0x55, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiskClient is the client API for Disk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiskClient interface {
	// ListDiskLocations returns locations <Adapter, Bus, Target, LUN ID> of all
	// disk devices enumerated by the host
	ListDiskLocations(ctx context.Context, in *ListDiskLocationsRequest, opts ...grpc.CallOption) (*ListDiskLocationsResponse, error)
	// ListDiskIDs returns all IDs (from IOCTL_STORAGE_QUERY_PROPERTY) of all disk
	// devices enumerated by the host
	ListDiskIDs(ctx context.Context, in *ListDiskIDsRequest, opts ...grpc.CallOption) (*ListDiskIDsResponse, error)
	// PartitionDisk initializes and partitions a disk device (if the disk has not
	// been partitioned already) and returns the resulting volume device ID
	PartitionDisk(ctx context.Context, in *PartitionDiskRequest, opts ...grpc.CallOption) (*PartitionDiskResponse, error)
	// Rescan refreshes the host's storage cache
	Rescan(ctx context.Context, in *RescanRequest, opts ...grpc.CallOption) (*RescanResponse, error)
}

type diskClient struct {
	cc *grpc.ClientConn
}

func NewDiskClient(cc *grpc.ClientConn) DiskClient {
	return &diskClient{cc}
}

func (c *diskClient) ListDiskLocations(ctx context.Context, in *ListDiskLocationsRequest, opts ...grpc.CallOption) (*ListDiskLocationsResponse, error) {
	out := new(ListDiskLocationsResponse)
	err := c.cc.Invoke(ctx, "/v1alpha1.Disk/ListDiskLocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskClient) ListDiskIDs(ctx context.Context, in *ListDiskIDsRequest, opts ...grpc.CallOption) (*ListDiskIDsResponse, error) {
	out := new(ListDiskIDsResponse)
	err := c.cc.Invoke(ctx, "/v1alpha1.Disk/ListDiskIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskClient) PartitionDisk(ctx context.Context, in *PartitionDiskRequest, opts ...grpc.CallOption) (*PartitionDiskResponse, error) {
	out := new(PartitionDiskResponse)
	err := c.cc.Invoke(ctx, "/v1alpha1.Disk/PartitionDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskClient) Rescan(ctx context.Context, in *RescanRequest, opts ...grpc.CallOption) (*RescanResponse, error) {
	out := new(RescanResponse)
	err := c.cc.Invoke(ctx, "/v1alpha1.Disk/Rescan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiskServer is the server API for Disk service.
type DiskServer interface {
	// ListDiskLocations returns locations <Adapter, Bus, Target, LUN ID> of all
	// disk devices enumerated by the host
	ListDiskLocations(context.Context, *ListDiskLocationsRequest) (*ListDiskLocationsResponse, error)
	// ListDiskIDs returns all IDs (from IOCTL_STORAGE_QUERY_PROPERTY) of all disk
	// devices enumerated by the host
	ListDiskIDs(context.Context, *ListDiskIDsRequest) (*ListDiskIDsResponse, error)
	// PartitionDisk initializes and partitions a disk device (if the disk has not
	// been partitioned already) and returns the resulting volume device ID
	PartitionDisk(context.Context, *PartitionDiskRequest) (*PartitionDiskResponse, error)
	// Rescan refreshes the host's storage cache
	Rescan(context.Context, *RescanRequest) (*RescanResponse, error)
}

// UnimplementedDiskServer can be embedded to have forward compatible implementations.
type UnimplementedDiskServer struct {
}

func (*UnimplementedDiskServer) ListDiskLocations(ctx context.Context, req *ListDiskLocationsRequest) (*ListDiskLocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDiskLocations not implemented")
}
func (*UnimplementedDiskServer) ListDiskIDs(ctx context.Context, req *ListDiskIDsRequest) (*ListDiskIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDiskIDs not implemented")
}
func (*UnimplementedDiskServer) PartitionDisk(ctx context.Context, req *PartitionDiskRequest) (*PartitionDiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartitionDisk not implemented")
}
func (*UnimplementedDiskServer) Rescan(ctx context.Context, req *RescanRequest) (*RescanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rescan not implemented")
}

func RegisterDiskServer(s *grpc.Server, srv DiskServer) {
	s.RegisterService(&_Disk_serviceDesc, srv)
}

func _Disk_ListDiskLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiskLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskServer).ListDiskLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Disk/ListDiskLocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskServer).ListDiskLocations(ctx, req.(*ListDiskLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Disk_ListDiskIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiskIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskServer).ListDiskIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Disk/ListDiskIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskServer).ListDiskIDs(ctx, req.(*ListDiskIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Disk_PartitionDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartitionDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskServer).PartitionDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Disk/PartitionDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskServer).PartitionDisk(ctx, req.(*PartitionDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Disk_Rescan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RescanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskServer).Rescan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Disk/Rescan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskServer).Rescan(ctx, req.(*RescanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Disk_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1alpha1.Disk",
	HandlerType: (*DiskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDiskLocations",
			Handler:    _Disk_ListDiskLocations_Handler,
		},
		{
			MethodName: "ListDiskIDs",
			Handler:    _Disk_ListDiskIDs_Handler,
		},
		{
			MethodName: "PartitionDisk",
			Handler:    _Disk_PartitionDisk_Handler,
		},
		{
			MethodName: "Rescan",
			Handler:    _Disk_Rescan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/kubernetes-csi/csi-proxy/client/api/disk/v1alpha1/api.proto",
}
